# Generated by Django 3.2.5 on 2021-08-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='href',
        ),
    ]
