# Generated by Django 3.2.5 on 2021-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210726_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='href',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
