# Generated by Django 3.2.5 on 2021-08-23 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210819_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_language',
            field=models.CharField(blank=True, max_length=32, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_profile_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Профиль вконтакте'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 17, 33, 10, 288817)),
        ),
    ]
